version: "3.3"
services:
  auth_service:
    depends_on:
      - postgres-auth
    build:
      context: ./auth_service/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - POSTGRES_HOST=172.28.0.3
      - METRICS_SERVICE_HOST=172.28.0.4
      - METRICS_SERVICE_PORT=8002
      - DEBUG=${DEBUG}
      - SERVER_API_KEY=${SERVER_API_KEY}
    networks:
      web:
        ipv4_address: 172.28.0.2
    ports:
      - 8001:8001
    volumes:
      - user-photos-volume:/usr/src/app/user-photos
  postgres-auth:
    image: postgres:13
    networks:
      web:
        ipv4_address: 172.28.0.3
    ports:
      - 5433:5432
    volumes:
      - db-auth-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - PGDATA=/var/lib/postgresql/data
  metrics_service:
    depends_on:
      - postgres-metrics
      - auth_service
    build:
      context: ./metrics_service/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - POSTGRES_HOST=172.28.0.5
      - AUTH_API_HOST=172.28.0.2
      - AUTH_API_PORT=8001
      - DEBUG=${DEBUG}
      - SERVER_API_KEY=${SERVER_API_KEY}
    networks:
      web:
        ipv4_address: 172.28.0.4
    ports:
      - 8002:8002
  postgres-metrics:
    image: postgres:13
    networks:
      web:
        ipv4_address: 172.28.0.5
    ports:
      - 5434:5432
    volumes:
      - db-metrics-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - PGDATA=/var/lib/postgresql/data
  document_service:
    depends_on:
      - postgres-document
    build:
      context: ./document_service/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - POSTGRES_HOST=172.28.0.11
      - AUTH_SERVICE_HOST=172.28.0.2
      - AUTH_SERVICE_PORT=8001
      - DEBUG=${DEBUG}
      - SERVER_API_KEY=${SERVER_API_KEY}
    networks:
      web:
        ipv4_address: 172.28.0.10
    ports:
      - 8003:8003
    volumes:
      - documents-volume:/usr/src/app/document-files
  postgres-document:
    image: postgres:13
    networks:
      web:
        ipv4_address: 172.28.0.11
    ports:
      - 5437:5432
    volumes:
      - db-document-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - PGDATA=/var/lib/postgresql/data
networks:
  web:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
volumes:
  user-photos-volume:
    external: true
  documents-volume:
    external: true
  db-auth-volume:
    external: true
  db-metrics-volume:
    external: true
  db-document-volume:
    external: true
