"""meter_fields_added

Revision ID: 6a5d2f4254c9
Revises: 18226c7f68e6
Create Date: 2021-05-11 22:51:21.542946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5d2f4254c9'
down_revision = '18226c7f68e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meters', sa.Column('average_days_per_week_usage', sa.Integer(), nullable=True))
    op.add_column('meters', sa.Column('average_hours_per_day_usage', sa.Integer(), nullable=True))
    op.add_column('meters', sa.Column('is_working', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meters', 'is_working')
    op.drop_column('meters', 'average_hours_per_day_usage')
    op.drop_column('meters', 'average_days_per_week_usage')
    # ### end Alembic commands ###
