"""equipment

Revision ID: b98b07aa42e6
Revises: a712f0e43b91
Create Date: 2021-05-09 16:16:39.604305

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b98b07aa42e6'
down_revision = 'a712f0e43b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('floor_id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Enum('Room', 'Meter', name='flooritemtype'), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('electric_equipment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('room_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('group',
                              sa.Enum('LabEquipment', 'HouseholdEquipment', 'ComputerEquipment', 'ClimateEquipment',
                                      'LightningEquipment', name='electricequipmentgroup'), nullable=False),
                    sa.Column('type',
                              sa.Enum('Engine', 'Workbench', 'Fridge', 'Microwave', 'Kettle', 'Monitor', 'Tower',
                                      'Printer', 'Conditioner', 'Heater', 'FanHeater', 'FanConvector', 'LED', 'Halogen',
                                      'Fluorescent', 'Incandescent', 'Luminescent', name='electricequipmenttype'),
                              nullable=False),
                    sa.Column('power_per_unit', sa.Numeric(), nullable=True),
                    sa.Column('subtype', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('heating_batteries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('room_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('type',
                              sa.Enum('CastIron', 'Registered', 'Panel', 'Aluminium', name='heatingbatterytype'),
                              nullable=False),
                    sa.Column('sections', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('water_equipment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('room_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Enum('Toilet', 'Bath', 'Shower', 'Pissoir', name='waterequipmenttype'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('windows',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('room_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Enum('Wood', 'Plastic', 'Aluminium', name='windowtype'), nullable=False),
                    sa.Column('thickness', sa.Numeric(), nullable=True),
                    sa.Column('glazing_formula', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('windows')
    op.drop_table('water_equipment')
    op.drop_table('heating_batteries')
    op.drop_table('electric_equipment')
    op.drop_table('floor_items')
    # ### end Alembic commands ###
