"""uniqueness

Revision ID: b532d45f6871
Revises: 8b5306e29214
Create Date: 2021-05-06 21:28:28.885412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b532d45f6871'
down_revision = '8b5306e29214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'electricity_meter_snapshots', ['snapshot_id'])
    op.create_unique_constraint(None, 'electricity_meters', ['meter_id'])
    op.create_unique_constraint(None, 'heat_meter_snapshots', ['snapshot_id'])
    op.alter_column('meters', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'water_meter_snapshots', ['snapshot_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'water_meter_snapshots', type_='unique')
    op.alter_column('meters', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'heat_meter_snapshots', type_='unique')
    op.drop_constraint(None, 'electricity_meters', type_='unique')
    op.drop_constraint(None, 'electricity_meter_snapshots', type_='unique')
    # ### end Alembic commands ###
