"""snapshot_changes

Revision ID: 3098b0b1453d
Revises: 6a5d2f4254c9
Create Date: 2021-05-12 15:20:04.748502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3098b0b1453d'
down_revision = '6a5d2f4254c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    op.drop_table('water_meter_snapshots')
    op.add_column('electricity_meter_snapshots', sa.Column('current', sa.Numeric(), nullable=True))
    op.add_column('electricity_meter_snapshots', sa.Column('voltage', sa.Numeric(), nullable=False))
    op.drop_column('electricity_meter_snapshots', 'current_voltage')
    op.add_column('meter_snapshots', sa.Column('automatic', sa.Boolean(), nullable=False))
    op.add_column('meter_snapshots', sa.Column('consumption', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meter_snapshots', 'consumption')
    op.drop_column('meter_snapshots', 'automatic')
    op.add_column('electricity_meter_snapshots', sa.Column('current_voltage', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('electricity_meter_snapshots', 'voltage')
    op.drop_column('electricity_meter_snapshots', 'current')
    op.create_table('water_meter_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consumption', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['meter_snapshots.id'], name='water_meter_snapshots_snapshot_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='water_meter_snapshots_pkey'),
    sa.UniqueConstraint('snapshot_id', name='water_meter_snapshots_snapshot_id_key')
    )
    op.create_table('readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name='readings_meter_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='readings_pkey')
    )
    # ### end Alembic commands ###
