"""heat

Revision ID: a712f0e43b91
Revises: b532d45f6871
Create Date: 2021-05-08 13:36:35.507358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a712f0e43b91'
down_revision = 'b532d45f6871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('floors', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('heat_meter_snapshots', sa.Column('heat_consumption', sa.Numeric(), nullable=True))
    op.add_column('heat_meter_snapshots', sa.Column('incoming_pump_usage', sa.Numeric(), nullable=True))
    op.add_column('heat_meter_snapshots', sa.Column('incoming_temperature', sa.Numeric(), nullable=True))
    op.add_column('heat_meter_snapshots', sa.Column('incoming_water_pressure', sa.Numeric(), nullable=True))
    op.add_column('heat_meter_snapshots', sa.Column('inside_temperature', sa.Numeric(), nullable=True))
    op.add_column('heat_meter_snapshots', sa.Column('outgoing_pump_usage', sa.Numeric(), nullable=True))
    op.add_column('heat_meter_snapshots', sa.Column('outgoing_temperature', sa.Numeric(), nullable=True))
    op.add_column('heat_meter_snapshots', sa.Column('outgoing_water_pressure', sa.Numeric(), nullable=True))
    op.add_column('heat_meter_snapshots', sa.Column('outside_temperature', sa.Numeric(), nullable=True))
    op.drop_column('heat_meter_snapshots', 'current_voltage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heat_meter_snapshots', sa.Column('current_voltage', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('heat_meter_snapshots', 'outside_temperature')
    op.drop_column('heat_meter_snapshots', 'outgoing_water_pressure')
    op.drop_column('heat_meter_snapshots', 'outgoing_temperature')
    op.drop_column('heat_meter_snapshots', 'outgoing_pump_usage')
    op.drop_column('heat_meter_snapshots', 'inside_temperature')
    op.drop_column('heat_meter_snapshots', 'incoming_water_pressure')
    op.drop_column('heat_meter_snapshots', 'incoming_temperature')
    op.drop_column('heat_meter_snapshots', 'incoming_pump_usage')
    op.drop_column('heat_meter_snapshots', 'heat_consumption')
    op.alter_column('floors', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
