"""floor_item_position

Revision ID: 18226c7f68e6
Revises: b98b07aa42e6
Create Date: 2021-05-10 12:47:41.663926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18226c7f68e6'
down_revision = 'b98b07aa42e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floor_items', sa.Column('position_x', sa.Numeric(), nullable=False))
    op.add_column('floor_items', sa.Column('position_y', sa.Numeric(), nullable=False))
    op.alter_column('floor_items', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('floor_items', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('floor_items', 'position_y')
    op.drop_column('floor_items', 'position_x')
    # ### end Alembic commands ###
