"""init

Revision ID: 8b5306e29214
Revises: 
Create Date: 2021-05-06 20:50:15.900360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5306e29214'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('building_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('photo_document_id', sa.Integer(), nullable=True),
    sa.Column('construction_type', sa.String(), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('climate_zone', sa.String(), nullable=True),
    sa.Column('heat_supply_contract_id', sa.Integer(), nullable=True),
    sa.Column('electricity_supply_contract_id', sa.Integer(), nullable=True),
    sa.Column('water_supply_contract_id', sa.Integer(), nullable=True),
    sa.Column('operation_schedule', sa.String(length=255), nullable=True),
    sa.Column('operation_hours_per_year', sa.Integer(), nullable=True),
    sa.Column('studying_daytime', sa.Integer(), nullable=False),
    sa.Column('studying_evening_time', sa.Integer(), nullable=False),
    sa.Column('studying_part_time', sa.Integer(), nullable=False),
    sa.Column('working_teachers', sa.Integer(), nullable=False),
    sa.Column('working_science', sa.Integer(), nullable=False),
    sa.Column('working_help', sa.Integer(), nullable=False),
    sa.Column('living_quantity', sa.Integer(), nullable=False),
    sa.Column('utilized_space', sa.Numeric(), nullable=True),
    sa.Column('utility_space', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['building_type_id'], ['building_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('index', sa.String(length=255), nullable=False),
    sa.Column('height', sa.Numeric(), nullable=True),
    sa.Column('floor_plan_document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Water', 'Gas', 'Heat', 'Electricity', name='metertype'), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('model_number', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=False),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('installation_notes', sa.String(length=255), nullable=True),
    sa.Column('accounting_number', sa.String(length=255), nullable=True),
    sa.Column('related_contract_number', sa.String(length=255), nullable=True),
    sa.Column('last_verification_date', sa.DateTime(), nullable=True),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('other_notes', sa.String(length=255), nullable=True),
    sa.Column('verification_interval_sec', sa.Integer(), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('recognition_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('responsible_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=255), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('responsibility', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=255), nullable=False),
    sa.Column('transformation_coefficient', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meter_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Water', 'Gas', 'Heat', 'Electricity', name='metertype'), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('current_time', sa.DateTime(), nullable=True),
    sa.Column('uptime', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('meter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(length=255), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Numeric(), nullable=True),
    sa.Column('responsible_department', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_meter_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('current_voltage', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['meter_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heat_meter_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('current_voltage', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['meter_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_meter_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('consumption', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['meter_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_meter_snapshots')
    op.drop_table('heat_meter_snapshots')
    op.drop_table('electricity_meter_snapshots')
    op.drop_table('rooms')
    op.drop_table('readings')
    op.drop_table('meter_snapshots')
    op.drop_table('electricity_meters')
    op.drop_table('responsible_users')
    op.drop_table('meters')
    op.drop_table('floors')
    op.drop_table('buildings')
    op.drop_table('locations')
    op.drop_table('building_types')
    # ### end Alembic commands ###
