"""environmental_readings

Revision ID: 04f776f46cd2
Revises: 3098b0b1453d
Create Date: 2021-05-12 15:40:56.344851

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '04f776f46cd2'
down_revision = '3098b0b1453d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmental_readings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('room_id', sa.Integer(), nullable=False),
                    sa.Column('automatic', sa.Boolean(), nullable=True),
                    sa.Column('current_time', sa.DateTime(), nullable=False),
                    sa.Column('temperature', sa.Numeric(), nullable=True),
                    sa.Column('humidity', sa.Numeric(), nullable=True),
                    sa.Column('notes', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environmental_readings')
    # ### end Alembic commands ###
