# Generated by Django 3.1.4 on 2021-04-21 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('secret_key', models.CharField(db_index=True, default=users.utils.generate_secret_key, max_length=511, unique=True)),
                ('expiration_date', models.DateTimeField(default=users.utils.generate_expiration_date)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
