# Generated by Django 3.1.4 on 2021-04-24 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_group',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
