# Generated by Django 3.1.4 on 2021-05-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='permissions',
            field=models.JSONField(default=list),
        ),
    ]
